apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

labels:
- includeSelectors: true
  pairs:
    app: it-request
configMapGenerator:
  - name: it-request-config
    namespace: production
    envs: [.env]
    behavior: create